Update composer.json to allow PHP 8
martin-helmich/phpunit-json-assert pull request #24
Opened 2020-08-25 06:51 UTC by sanmai

2020-08-25 16:20 UTC, martin-helmich commented
Thanks for this PR! Unfortunately, after enabling the actual pipelines for this PR, I've noticed that currently Composer is not able to resolve a compatible set of dependencies for this project for PHP 8 -- mainly because there's no PHP 8-compatible version of phpspec/prophecy (already tracked at phpspec/prophecy#491). So there's no way the new CI jobs would pass with PHP 8.

I'll sit on this for a while -- hopefully, this'll resolve itself in the next few days.

Oh, and we'd also need to exclude the "PHP 8"+"PHPUnit 8" combination from the build matrix, since PHPUnit 8 is declared to be compatible with PHP `^7.2`, only.

2020-08-25 16:21 UTC, martin-helmich requested changes

2020-08-25 16:21 UTC, martin-helmich commented on .github/workflows/php.yml
>          exclude:
```suggestion
        exclude:
          - php: '8.0'
            phpunit: '8.0'
```

2020-08-26 00:25 UTC, sanmai commented
Thanks for the review! I made it such so failures on 8.0 would not affect the entire build. This should work, but let me try with something else too.

2020-08-26 00:55 UTC, sanmai commented
Alright, it is as good as it gets. Hope you can squash-merge it.

I added a pretty name for the builds, you might want to update your protected branch configuration. Or we can restore the old naming scheme.

2020-08-26 05:12 UTC, martin-helmich approved these changes

2020-08-26 05:12 UTC, merged

2020-08-26 05:12 UTC, martin-helmich commented
:+1: Looking good! Thanks for your contribution.